---
abstract: 'Simply parse String into tokens with rules which are similar to Lex.'
author:
  - 'khs <sng2nara@gmail.com>'
build_requires:
  Data::Dumper: '0'
  Data::Printer: '0'
  Test::More: '0'
  lib: '0'
  strict: '0'
  warnings: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.013, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Parse-Token-Lite
requires:
  Carp: '0'
  Data::Dump: '0'
  Exporter: '0'
  Log::Log4perl: '0'
  Moose: '0'
resources:
  homepage: https://github.com/sng2c/Parse-Token-Lite
  repository: git://github.com/sng2c/Parse-Token-Lite.git
version: '0.200'
